data_dir: target/vector-data

sources:
  in:
    type: stdin

sinks:
  hec:
    type: splunk_hec_logs
    inputs: ["in"]
    endpoint: "http://127.0.0.1:18088"
    default_token: "dev-token"
    endpoint_target: "raw"
    encoding:
      codec: text
    compression: none
    acknowledgements:
      enabled: false
      indexer_acknowledgements_enabled: false
